# Grid size of client in pixels
grid_size = 25

[World]
# World size, in pixels
size_x = 3000
size_y = 3000
# Number of teams
teams = 16
food_per_player = 10
# Collect this many points to win the game
# Put a non-positive number to disable this
maximum_points = 300
maximum_food_per_team = 100
# Points you get when collecting your own team's food
own_team_food_points = 3
# Points you get when collecting other teams' food
other_team_food_points = 1
food_regeneration = 2

[Visibility]
# Rows are self, columns are others (self looking at other)
# -1 for invisible
player = [
  #  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
  [  0, 11,  1,  3, 13,  9, 15,  7,  4, 15, -1, -1,  7, 13, 14,  9],
  [ 14,  1,  2, 13,  4,  6,  6,  3,  8, 14,  0, 11,  3,  5,  4,  4],
  [ 14, 12,  2,  3,  6, 12,  8,  2,  8,  9,  2,  5, 12,  5, 14, 15],
  [  0, 11,  2,  3,  4,  3, -1,  7,  7,  4, -1, 11, 10,  4, 14,  8],
  [  0,  1, 15, 13,  4, 12,  6,  2,  8,  1, 10, 11, -1,  8, 14,  9],
  [  6,  0,  2,  3, 11,  5, 15,  7,  6,  9,  0, -1,  6, 13,  8,  9],
  [  0,  0,  5, 12,  4,  5,  6,  7, 15, 10, 10,  6, 12,  1,  8,  5],
  [  0,  1,  8, -1,  4,  3,  7,  7,  1,  8, 12, 15, 15,  1, 14, 15],
  [  0,  9, 14,  0, 15,  4,  6, 12,  8, 13, 13,  8, 12, 13,  5, 13],
  [ 12,  2,  8,  1,  4,  5,  9,  7,  8,  9,  0,  9,  5,  6, 14, 15],
  [  0,  9, 14, 15, 10, 14, -1,  7,  4,  9, 10, 12,  6,  5,  1, 12],
  [  0, 12,  7,  3,  4,  5, 14,  7, 11, 14,  4, 11, 12, 13, 11, 15],
  [  0,  9,  2,  3,  4,  5,  9, -1,  8,  9,  0, -1, 12, 13,  4, 15],
  [  0,  1,  3, 10, 12,  2,  8,  7,  1,  9, 10, 12, 12, 13,  1, 13],
  [  5,  2,  4, 11, 15,  5,  6,  7,  8,  9, 10, 11, 15, 10, 14,  0],
  [ -1,  8,  2,  3,  4,  5,  3, 12,  8,  7, 10, 12, 12, 12,  2, 15],
]

food_visible = [
  #  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
  [  0,  8, -1,  2, 15, -1,  6,  6,  8,  0, 12, 11, 12, 13,  5,  4],
  [ 15,  1,  9,  0, 12,  5, 11,  7,  8,  6,  2, 12, 12, 13,  2, 15],
  [  0, 10,  2, 11, 15,  0,  6,  6,  4, -1, 10,  0,  7, -1,  3,  6],
  [  0,  1,  5,  3,  0,  9,  9,  7,  7,  9, 13,  0,  3, 13, 14, 14],
  [  0, 11,  2,  3,  4, -1,  0,  7, 14,  7, 10,  2,  7,  4, -1,  6],
  [  0,  2,  2,  3,  6,  5, 12,  9,  8,  9,  5, 11,  3, 13,  4, 10],
  [ 11,  4, 12, 11,  7,  4,  6, 12,  8,  9, -1, 13, 15, 13, 11,  8],
  [  9,  4,  5,  3,  4,  5,  1,  7,  8, 11,  4, 11, 14, 10,  9,  4],
  [  0,  8, 14,  7,  7, 15,  6,  6,  8,  9,  1,  4, 12, 12,  7,  6],
  [  9,  1,  2, 10,  0,  5, 15,  7,  9,  9, 15, 11,  9, 13, 15, 15],
  [ 10,  1,  2,  3,  5,  5,  6,  3,  7,  2, 10,  3,  1,  0,  0,  9],
  [  2,  1,  4,  6,  0,  6,  1,  9,  9, 14,  4, 11,  8, 15, 11, 15],
  [  2,  0, 10, 14, 15,  5,  6,  7,  8, -1, -1, 15, 12,  4, 10, 15],
  [  0,  7, 10, 12,  1,  0,  6, 13,  8,  9, 10,  4,  2, 13, 14,  8],
  [  0, -1, 13,  6,  7, 11,  6,  6,  8,  8,  2, -1,  7,  0, 14,  3],
  [  7, 12,  2,  4,  4,  8,  2,  3,  8,  9, -1,  0,  7,  6, 14, 15],
]

# 1 = can eat, 0 = can't eat
food_eatable = [
  [  1,  0,  0,  1,  0,  1,  0,  1,  0,  0,  0,  0,  0,  1,  1,  0],
  [  0,  1,  1,  0,  1,  0,  1,  1,  0,  1,  1,  1,  1,  0,  0,  0],
  [  0,  1,  1,  1,  0,  1,  0,  1,  1,  1,  0,  1,  0,  0,  1,  0],
  [  1,  1,  0,  1,  1,  1,  0,  1,  0,  1,  0,  1,  0,  1,  0,  0],
  [  0,  0,  0,  1,  1,  0,  0,  1,  0,  1,  1,  0,  0,  0,  0,  1],
  [  0,  1,  0,  0,  1,  1,  0,  1,  0,  0,  1,  1,  0,  1,  1,  0],
  [  0,  0,  0,  0,  1,  0,  1,  1,  1,  0,  1,  0,  1,  1,  0,  0],
  [  1,  1,  1,  1,  1,  0,  1,  1,  0,  0,  1,  1,  0,  0,  1,  1],
  [  1,  1,  1,  0,  0,  0,  1,  1,  1,  0,  1,  1,  0,  1,  1,  1],
  [  1,  0,  0,  1,  1,  0,  1,  1,  1,  1,  1,  0,  0,  0,  1,  0],
  [  1,  1,  0,  1,  0,  1,  0,  1,  1,  1,  1,  0,  0,  1,  0,  0],
  [  1,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0,  1,  0],
  [  1,  1,  0,  0,  1,  1,  1,  1,  0,  0,  1,  1,  1,  0,  1,  1],
  [  1,  1,  0,  1,  0,  1,  0,  0,  1,  0,  0,  0,  1,  1,  1,  1],
  [  0,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1],
  [  0,  1,  1,  0,  1,  0,  1,  0,  0,  0,  0,  0,  1,  0,  1,  1],
]
