[System]
grid_size = 25

game_interval = 10

[World]
size_x = 6000
size_y = 6000

teams = 10

team_assignment = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

food_per_player = 20

maximum_points = 300

maximum_food_per_team = 300

[Team]
speed = [2, 3, 3, 7, 4, 2, 3, 3, 6, 2]

own_team_food_points = [3, 3, 3, 1, 5, 2, 3, 3, 4, 2]

other_team_food_points = [2, 2, 0, 0, 0, 1, 5, 1, 1, 1, 1]

food_regeneration = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

random_food_regeneration = [2, 2, 5, 2, 1, 1, 3, 1, 0, 0]

[Visibility]
player = [
  [  0,  1,  2,  3,  4,  5,  7,  2,  7,  9],
  [  9,  1,  1,  3,  9,  6,  6,  7,  8,  9],
  [  7,  1,  2,  3,  4,  5,  6,  6,  8,  9],
  [  0,  1,  2,  3,  4, -1,  8,  7,  6,  9],
  [  0,  1,  2,  3,  4,  5,  6,  7,  8, -1],
  [  8,  9,  7,  1,  2,  5,  6,  0,  6,  7],
  [  7,  4,  2,  3,  9, -1,  6,  7,  8,  9],
  [  0,  1,  9,  3,  6,  5,  6,  7,  8,  7],
  [  4,  8,  3,  3,  1,  5,  6,  7,  8,  3],
  [  5,  6,  4,  3,  4,  1,  6,  7,  8,  9],
]

food_visible = [
  [  0,  1,  2,  3,  4,  5,  6,  0,  8,  9],
  [  0,  1,  2,  0,  7,  5,  6,  8,  5,  0],
  [  7,  7,  2,  9,  4,  5,  6,  7,  8,  9],
  [  0,  1,  2,  3,  4,  4,  6,  3,  4,  0],
  [  0,  3,  2,  3,  4,  5,  6,  7,  8,  7],
  [  2,  3,  2,  3,  4,  5,  6,  7,  8,  9],
  [  0,  3,  3,  5,  4,  5,  6, -1,  8,  9],
  [ -1,  0,  2,  2,  3,  5,  6,  7,  8,  9],
  [  9,  1,  1,  8,  7,  5,  6,  2,  8,  9],
  [  0,  1,  2,  3,  4,  8,  6,  2,  8,  9],
]

food_eatable = [
  [  1,  0,  0,  1,  0,  0,  1,  1,  0,  1],
  [  0,  1,  1,  0,  0,  0,  1,  0,  1,  0],
  [  1,  1,  1,  0,  1,  0,  0,  1,  0,  0],
  [  0,  1,  1,  1,  1,  1,  1,  0,  0,  1],
  [  0,  0,  0,  0,  1,  0,  1,  1,  0,  0],
  [  0,  0,  1,  0,  1,  1,  1,  1,  0,  0],
  [  0,  1,  1,  1,  0,  0,  1,  1,  1,  1],
  [  0,  0,  1,  1,  1,  1,  1,  1,  0,  1],
  [  1,  0,  0,  1,  0,  0,  1,  1,  1,  0],
  [  1,  0,  0,  0,  1,  0,  0,  0,  0,  1],
]

scoreboard = [1, 0, 1, 1, 0, 0, 1, 1, 1, 0]
