# Grid size of client in pixels
grid_size = 25

[World]
# World size, in pixels
size_x = 3000
size_y = 3000
# Number of teams
teams = 4
# The order in which players are assigned teams
team_assignment = [0, 1, 2, 3]
#team_assignment = [3, 2, 0 ,1, 0, 0, 0, 0]
food_per_player = 10
# Collect this many points to win the game
# Put a non-positive number to disable this
maximum_points = 200
maximum_food_per_team = 100
# Points you get when collecting your own team's food
own_team_food_points = 3
# Points you get when collecting other teams' food
other_team_food_points = 1
food_regeneration = 0

[Visibility]
# Rows are self, columns are others (self looking at other)
# -1 for invisible
player = [
  [ 0, -1, -1, -1],
  [ 2,  1,  3,  0],
  [ 0,  1,  2,  3],
  [-1,  1, -1,  3],
]

food_visible = [
  [ 0, -1,  2, -1],
  [-1,  1, -1, -1],
  [ 0,  1,  2,  3],
  [ 3,  3,  3,  3],
]

# 1 = can eat, 0 = can't eat
food_eatable = [
  [1, 0, 1, 0],
  [0, 1, 0, 0],
  [0, 1, 1, 0],
  [0, 1, 0, 1],
]
