[System]
# Grid size of client in pixels
grid_size = 25

# Wait time between each game in seconds
game_interval = 5

[World]
# World size, in pixels
size_x = 3000
size_y = 3000

# Number of teams
teams = 4

# The order in which players are assigned teams
team_assignment = [0, 1, 2, 3, 1]

# Food added to the world per player connection
food_per_player = 10

# Collect this many points to win the game
# Put a non-positive number to disable this
maximum_points = 200

# No more food is generated after this many food is in the world
# Put a non-positive number to disable this
maximum_food_per_team = 100

# The number of food that's added to the world for every food a player eats
food_regeneration = 0

[Player]
# Must be a positive integer. 1 to 10 recommended.
speed = [2, 3, 5, 8]

# Points you get when collecting your own team's food
own_team_food_points = [3, 3, 1, 10]

# Points you get when collecting other teams' food
other_team_food_points = [1, 1, 0, 3]

[Visibility]
# Rows are self, columns are others (self looking at other)
# -1 for invisible
player = [
  [ 0, -1, -1, -1],
  [ 2,  1,  3,  0],
  [ 0,  1,  2,  3],
  [-1,  1, -1,  3],
]

food_visible = [
  [ 0, -1,  2, -1],
  [-1,  1, -1, -1],
  [ 0,  1,  2,  3],
  [ 3,  3,  3,  3],
]

# 1 = can eat, 0 = can't eat
food_eatable = [
  [1, 0, 1, 0],
  [0, 1, 0, 0],
  [0, 1, 1, 0],
  [0, 1, 0, 1],
]
