[World]
# World size, in pixels
size_x = 3000
size_y = 3000
# Number of teams
teams = 4
food_per_player = 10
maximum_food_per_team = 100
# Points you get when collecting your own team's food
own_team_food_points = 3
# Points you get when collecting other teams' food
other_team_food_points = 1

[Visibility]
# Rows are self, columns are others (self looking at other)
# -1 for invisible
player = [
  [ 0, -1, -1, -1],
  [ 2,  1,  3,  0],
  [ 0,  1,  2,  3],
  [-1,  1, -1,  3],
]

food_visible = [
  [ 0, -1,  2, -1],
  [-1,  1, -1, -1],
  [ 0,  1,  2,  3],
  [ 3,  3,  3,  3],
]

# Currently unimplemented
food_eatable = [
  [ 0, -1,  2, -1],
  [-1,  1, -1, -1],
  [ 0,  1,  2,  3],
  [ 3,  3,  3,  3],
]

